"""initial schema

Revision ID: 8d8658d0ed34
Revises: 
Create Date: 2026-07-07 09:54:55.067267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8658d0ed34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_publisher_id'), 'series', ['publisher_id'], unique=False)
    op.create_index(op.f('ix_series_slug'), 'series', ['slug'], unique=True)
    op.create_table('volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('volume_number', sa.Float(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volumes_isbn'), 'volumes', ['isbn'], unique=True)
    op.create_index(op.f('ix_volumes_series_id'), 'volumes', ['series_id'], unique=False)
    op.create_table('store_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volume_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_url', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_listings_store_id'), 'store_listings', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_listings_volume_id'), 'store_listings', ['volume_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['store_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_listing_id'), 'price_history', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_listing_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_store_listings_volume_id'), table_name='store_listings')
    op.drop_index(op.f('ix_store_listings_store_id'), table_name='store_listings')
    op.drop_table('store_listings')
    op.drop_index(op.f('ix_volumes_series_id'), table_name='volumes')
    op.drop_index(op.f('ix_volumes_isbn'), table_name='volumes')
    op.drop_table('volumes')
    op.drop_index(op.f('ix_series_slug'), table_name='series')
    op.drop_index(op.f('ix_series_publisher_id'), table_name='series')
    op.drop_table('series')
    op.drop_table('stores')
    op.drop_table('publishers')
    # ### end Alembic commands ###
