"""baseline schema

Revision ID: 7dc23731dcb8
Revises: 
Create Date: 2026-09-14 06:39:12.693483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_query', sa.String(length=200), nullable=False),
    sa.Column('last_query', sa.String(length=200), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stores_ok', sa.Integer(), nullable=False),
    sa.Column('stores_failed', sa.Integer(), nullable=False),
    sa.Column('results_found', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    with op.batch_alter_table('import_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_records_normalized_query'), ['normalized_query'], unique=True, if_not_exists=True)

    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publishers_normalized_name'), ['normalized_name'], unique=True, if_not_exists=True)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    if_not_exists=True
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_code'), ['code'], unique=True, if_not_exists=True)

    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('normalized_title', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publisher_id', 'normalized_title', name='uq_series_publisher_normalized_title'),
    sa.UniqueConstraint('publisher_id', 'slug', name='uq_series_publisher_slug'),
    if_not_exists=True
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_normalized_title'), ['normalized_title'], unique=False, if_not_exists=True)
        batch_op.create_index(batch_op.f('ix_series_publisher_id'), ['publisher_id'], unique=False, if_not_exists=True)

    op.create_table('catalog_series',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('mangakol_slug', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'mangakol_slug'),
    if_not_exists=True
    )
    op.create_table('volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('volume_number', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('collection_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'volume_number', name='uq_volume_series_number'),
    if_not_exists=True
    )
    with op.batch_alter_table('volumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volumes_isbn'), ['isbn'], unique=True, if_not_exists=True)
        batch_op.create_index(batch_op.f('ix_volumes_series_id'), ['series_id'], unique=False, if_not_exists=True)

    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('volume_id', sa.Integer(), nullable=False),
    sa.Column('threshold_price', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'volume_id', name='uq_price_alert_user_volume'),
    if_not_exists=True
    )
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_alerts_user_id'), ['user_id'], unique=False, if_not_exists=True)
        batch_op.create_index(batch_op.f('ix_price_alerts_volume_id'), ['volume_id'], unique=False, if_not_exists=True)

    op.create_table('store_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volume_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_url', sa.String(length=2000), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volume_id', 'store_id', name='uq_listing_volume_store'),
    if_not_exists=True
    )
    with op.batch_alter_table('store_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_listings_store_id'), ['store_id'], unique=False, if_not_exists=True)
        batch_op.create_index(batch_op.f('ix_store_listings_volume_id'), ['volume_id'], unique=False, if_not_exists=True)

    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('volume_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'volume_id', name='uq_wishlist_user_volume'),
    if_not_exists=True
    )
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_items_user_id'), ['user_id'], unique=False, if_not_exists=True)
        batch_op.create_index(batch_op.f('ix_wishlist_items_volume_id'), ['volume_id'], unique=False, if_not_exists=True)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['store_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_checked_at'), ['checked_at'], unique=False, if_not_exists=True)
        batch_op.create_index(batch_op.f('ix_price_history_listing_id'), ['listing_id'], unique=False, if_not_exists=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_listing_id'))
        batch_op.drop_index(batch_op.f('ix_price_history_checked_at'))

    op.drop_table('price_history')
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_items_volume_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_items_user_id'))

    op.drop_table('wishlist_items')
    with op.batch_alter_table('store_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_listings_volume_id'))
        batch_op.drop_index(batch_op.f('ix_store_listings_store_id'))

    op.drop_table('store_listings')
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_alerts_volume_id'))
        batch_op.drop_index(batch_op.f('ix_price_alerts_user_id'))

    op.drop_table('price_alerts')
    with op.batch_alter_table('volumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volumes_series_id'))
        batch_op.drop_index(batch_op.f('ix_volumes_isbn'))

    op.drop_table('volumes')
    op.drop_table('catalog_series')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_publisher_id'))
        batch_op.drop_index(batch_op.f('ix_series_normalized_title'))

    op.drop_table('series')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_code'))

    op.drop_table('stores')
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publishers_normalized_name'))

    op.drop_table('publishers')
    with op.batch_alter_table('import_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_records_normalized_query'))

    op.drop_table('import_records')
    # ### end Alembic commands ###
